<a href="https://colab.research.google.com/github/youssefbourais0310/Machine_learning_classification/blob/main/make_prediction_using_machine_learning_model_%5Bpredict()_VS_predict_proba()%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **predict()_VS_predict.proba()**

In [1]:
# Standard imports
import numpy as np 
import pandas as pd 

In [2]:
#1.get the data ready  
heart_disease = pd.read_csv("/content/drive/MyDrive/heart-disease.csv")     
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [3]:
len(heart_disease)

303

In [4]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import  RandomForestClassifier
from sklearn.model_selection import train_test_split

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target" , axis = 1)
y = heart_disease  ["target"] 

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#instatiate RandomForestClassifier
Clf = RandomForestClassifier()

# Fit the model to the data(training the machine learning model  )
Clf.fit(X_train , y_train )

#evaluate the RandomForestClassifier(use the patterns the model has learned )
Clf.score(X_test , y_test)

0.8524590163934426

In [5]:
X.head()

age  sex  cp  trestbps  chol  fbs  ...  thalach  exang  oldpeak  slope  ca  thal
0   63    1   3       145   233    1  ...      150      0      2.3      0   0     1
1   37    1   2       130   250    0  ...      187      0      3.5      0   0     2
2   41    0   1       130   204    0  ...      172      0      1.4      2   0     2
3   56    1   1       120   236    0  ...      178      0      0.8      2   0     2
4   57    0   0       120   354    0  ...      163      1      0.6      2   0     2

[5 rows x 13 columns]

In [6]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

In [7]:
X_test.head()

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
179   57    1   0       150   276  ...      1      0.6      1   1     1
228   59    1   3       170   288  ...      0      0.2      1   0     3
111   57    1   2       150   126  ...      0      0.2      2   1     3
246   56    0   0       134   409  ...      1      1.9      1   2     3
60    71    0   2       110   265  ...      0      0.0      2   1     2

[5 rows x 13 columns]

In [8]:
Clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [9]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [10]:
 # Compare predictions to truth labels to evaluate the model 
 y_preds = Clf.predict(X_test)
 np.mean(y_preds == y_test)

0.8524590163934426

In [11]:
Clf.score(X_test , y_test)

0.8524590163934426

In [12]:
from sklearn.metrics import  accuracy_score
accuracy_score(y_test,y_preds)


0.8524590163934426

Make prediction with predict_proba()

In [20]:
#predict_proba() returns probabilities of a classification label (0.1)
Clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [18]:
#lets predict() on the same data..
Clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])

In [19]:
X_test[:5]

age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
179   57    1   0       150   276  ...      1      0.6      1   1     1
228   59    1   3       170   288  ...      0      0.2      1   0     3
111   57    1   2       150   126  ...      0      0.2      2   1     3
246   56    0   0       134   409  ...      1      1.9      1   2     3
60    71    0   2       110   265  ...      0      0.0      2   1     2

[5 rows x 13 columns]

In [21]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64